name: macos

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        buildtype: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          wget -q https://github.com/macports/macports-base/releases/download/v2.8.1/MacPorts-2.8.1-12-Monterey.pkg
          sudo installer -pkg ./MacPorts-2.8.1-12-Monterey.pkg -target /
          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
          sudo port selfupdate -N
          sudo port install libsdl2 +universal -N
          sudo port install libsdl2_mixer +universal -N
          sudo port install libsdl2_image +universal -N
          mkdir ~/macports
          sudo cp -R /opt/local ~/macports
          sudo chown -R $USER:staff ~/macports

      - name: Configure FreeSerf
        run: |
          cmake -B build -G "Unix Makefiles"

      - name: Check style
        run: |
          cd build
          make check_style

      - name: Build FreeSerf
        run: |
          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
          cd build
          make

      - name: Run Tests
        run: |
          cd build
          make test

      - name: Pack FreeSerf
        run: |
          cd build
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: FreeSerf-${{ matrix.buildtype }}
          path: ./build/FreeSerf.dmg
